# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/8200666/Desktop/mpsis/mpsis.cache/wt [current_project]
set_property parent.project_path C:/Users/8200666/Desktop/mpsis/mpsis.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/8200666/Desktop/mpsis/mpsis.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/defines_riscv.vh
read_mem C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/my_program.mem
read_verilog -library xil_defaultlib {
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/ALU.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/data_mem.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/decoder_riscv.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/fulladder.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/fulladder32.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/fulladder4.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/instr_mem.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/led_sb_ctrl.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/rf_riscv.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/riscv_core.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/sw_sb_ctrl.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/sys_clk_rst_gen.v
  C:/Users/8200666/Desktop/mpsis/mpsis.srcs/sources_1/new/riscv_unit.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/8200666/Desktop/mpsis/mpsis.srcs/constrs_1/new/nexys_a7_100t.xdc
set_property used_in_implementation false [get_files C:/Users/8200666/Desktop/mpsis/mpsis.srcs/constrs_1/new/nexys_a7_100t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top riscv_unit -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_unit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_unit_utilization_synth.rpt -pb riscv_unit_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
